# Generated by Django 4.2.13 on 2024-06-20 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoupload',
            name='title',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='VideoDecode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(choices=[('en', 'English'), ('bn', 'Bangla'), ('hi', 'Hindi'), ('fr', 'French'), ('es', 'Spanish'), ('zh-CN', 'Chinese'), ('ar', 'Arabic'), ('de', 'German'), ('it', 'Italian'), ('ja', 'Japanese'), ('pk', 'Pakistani')], max_length=20)),
                ('original_text', models.TextField(blank=True, null=True)),
                ('converted_text', models.TextField(blank=True, null=True)),
                ('video_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decodes', to='video.videoupload')),
            ],
        ),
    ]
